### PR TITLE
BA-1305: Inject up-to-date claims to access token on refresh

### PR DESCRIPTION
**Pull request by pablogadhi**
This fixes the issues with the user update flows, where the token has stale data. Whenever we update the user's data, we can just call `refreshAccessToken(ACCESS_COOKIE_NAME, REFRESH_COOKIE_NAME)` on success and that should get a new access token with the fresh user data and save it to the cookie. In my tests I also updated the useUser hook to be like the following:
```
import { useEffect, useState } from 'react'

import { getUser } from '@baseapp-frontend/authentication'

import { IUser } from 'types/user'

export const useUser = () => {
  const [user, setUser] = useState<Partial<IUser> | null>(null)

  useEffect(() => {
    const syncGetUser = async () => {
      setUser(await getUser())
    }

    syncGetUser()
  }, [])

  return user
}
```
because I wasn't sure if the getUser function can be used directly in a react hook, since it's async. Just FYI if that helps someone.

### CODE REVIEW

**Review by Janekk — APPROVED** [review]
Looks good :) maybe we can update the README of baseapp_auth with the new setting and metioned that it will be used by default.

**Review by anicioalexandre — APPROVED** [review]
working nice!

**Comment by nossila** [comment]
@pablogadhi maybe also increase the version so we can release the update? :)

**Comment by pablogadhi** [comment]
Updated the docs to talk about the default settings and bumped the package version up.

**Pull request merged**
